name: Build the project

on:
  push:
    branches: [ main ]  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repo
        uses: actions/checkout@v4

      - name: Build the code
        run: |
          sudo apt install -y build-essential python-is-python3
          make
      - name: Install dependencies for tests
        run: |
          python -m pip install pytest
      - name: Run tests
        run: |
          pytest
